TRIM_WIDTH_INCHES = 6.0
TRIM_HEIGHT_INCHES = 9.0

PREVIEW_HEIGHT_PIXELS = 600
PIXELS_PER_INCH = PREVIEW_HEIGHT_PIXELS / TRIM_HEIGHT_INCHES

TOP_MARGIN_INCHES = 0.75
BOTTOM_MARGIN_INCHES = 0.75
OUTSIDE_MARGIN_INCHES = 0.50

PREVIEW_WIDTH_PIXELS = round(
    PREVIEW_HEIGHT_PIXELS
    * TRIM_WIDTH_INCHES
    / TRIM_HEIGHT_INCHES
)

FIRST_LINE_INDENT_INCHES = 0.30

KDP_MAX_PAGE_COUNT = 828

DEFAULT_MARGIN_PROFILE = "Standard"

MARGIN_PROFILES = {
    "Standard": {
        "top": 0.75,
        "bottom": 0.75,
        "outside": 0.50,
    },
    "Compact KDP": {
        "top": 0.50,
        "bottom": 0.50,
        "outside": 0.375,
    },
    "Minimum KDP": {
        "top": 0.25,
        "bottom": 0.25,
        "outside": 0.25,
    },
}

CHAPTER_HEADING_FONT_SIZE = 16
CHAPTER_HEADING_SPACE_AFTER_INCHES = 0.25

PREVIEW_BORDER_PIXELS = 1