TRIM_WIDTH_INCHES = 6.0
TRIM_HEIGHT_INCHES = 9.0

PREVIEW_HEIGHT_PIXELS = 600
PIXELS_PER_INCH = PREVIEW_HEIGHT_PIXELS / TRIM_HEIGHT_INCHES

TOP_MARGIN_INCHES = 0.75
BOTTOM_MARGIN_INCHES = 0.75
OUTSIDE_MARGIN_INCHES = 0.50

PREVIEW_WIDTH_PIXELS = round(
    PREVIEW_HEIGHT_PIXELS
    * TRIM_WIDTH_INCHES
    / TRIM_HEIGHT_INCHES
)